[package]
name = "tac"
edition = "2021"
version = "2.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
description = "Print lines from file in reverse order"
homepage = "https://github.com/neosmart/tac"
repository = "https://github.com/neosmart/tac"
readme = "README.md"
keywords = ["tac", "reverse", "core", "utils"]
categories = ["command-line-utilities"]
rust-version = "1.70"
license = "MIT"

[dependencies]
memmap2 = "0.9"
